// ============================================================
// RECIPE DATA
// Add your own recipes here! Each recipe needs:
//   id        - unique string
//   name      - display name
//   calories  - estimated calories per serving
//   health    - "healthy" | "balanced" | "indulgent" (Gnommy)
//   griddle   - true if it cooks on the Blackstone flat-top (optional)
//   time      - total cook time in minutes
//   tags      - array of labels shown on the card
//   steps     - array of instruction strings
//   ingredients - array of { item, amount, dept, search }
//     item   - display name of the ingredient
//     amount - quantity (recipes are portioned for two)
//     dept   - Publix department (must match a key in DEPARTMENTS below)
//     search - (optional) term used for the Publix link; defaults to item
// ============================================================

// Common allergens used for filtering. Each recipe lists which of
// these it contains in its `allergens` array (use the lowercase keys).
// Filter chips in the app are generated dynamically from whatever
// allergens actually appear in the recipe list below.
const ALLERGENS = {
  shellfish: "Shellfish",
  nuts: "Nuts",
  fish: "Fish",
  dairy: "Dairy",
  gluten: "Gluten",
  eggs: "Eggs",
  soy: "Soy",
};

// Health styles. "indulgent" is Gnommy mode: maximum tastiness,
// calories optional reading.
const HEALTH_LEVELS = {
  healthy:   { label: "Healthy" },
  balanced:  { label: "Balanced" },
  indulgent: { label: "Gnommy" },
};

// Departments in roughly the order you'd walk a Publix,
// used to group/sort the weekly shopping list.
const DEPARTMENTS = {
  "Produce":        { order: 1 },
  "Bakery":         { order: 2 },
  "Deli":           { order: 3 },
  "Meat":           { order: 4 },
  "Seafood":        { order: 5 },
  "Dairy":          { order: 6 },
  "Frozen":         { order: 7 },
  "Pantry":         { order: 8 },
  "Spices":         { order: 9 },
  "International":  { order: 10 },
};

const RECIPES = [
  {
    id: "lemon-garlic-salmon",
    calories: 520,
    health: "healthy",
    allergens: ["fish", "dairy"],
    name: "Lemon Garlic Butter Salmon",
    time: 25,
    tags: ["Seafood", "One Pan", "Light"],
    ingredients: [
      { item: "Salmon fillets", amount: "2 (6 oz each)", dept: "Seafood", search: "fresh salmon fillet" },
      { item: "Asparagus", amount: "1 bunch", dept: "Produce" },
      { item: "Lemon", amount: "1", dept: "Produce" },
      { item: "Garlic", amount: "3 cloves", dept: "Produce" },
      { item: "Butter", amount: "3 tbsp", dept: "Dairy", search: "unsalted butter" },
      { item: "Fresh parsley", amount: "2 tbsp, chopped", dept: "Produce" },
      { item: "Olive oil", amount: "1 tbsp", dept: "Pantry" },
    ],
    steps: [
      "Preheat oven to 400°F. Line a sheet pan with foil.",
      "Toss asparagus with olive oil, salt, and pepper; arrange on one side of the pan.",
      "Place salmon on the other side. Melt butter with minced garlic and pour over the salmon.",
      "Top with lemon slices and bake 12–15 minutes until salmon flakes easily.",
      "Finish with chopped parsley and a squeeze of lemon.",
    ],
  },
  {
    id: "chicken-fajita-skillet",
    griddle: true,
    calories: 640,
    health: "balanced",
    allergens: ["dairy", "gluten"],
    name: "Chicken Fajita Skillet",
    time: 30,
    tags: ["Mexican", "One Pan"],
    ingredients: [
      { item: "Chicken breasts", amount: "1 lb, sliced", dept: "Meat", search: "boneless chicken breast" },
      { item: "Bell peppers", amount: "2 (any color)", dept: "Produce", search: "bell pepper" },
      { item: "Yellow onion", amount: "1, sliced", dept: "Produce" },
      { item: "Fajita seasoning", amount: "2 tbsp", dept: "Spices" },
      { item: "Flour tortillas", amount: "6 small", dept: "International", search: "flour tortillas" },
      { item: "Lime", amount: "1", dept: "Produce" },
      { item: "Sour cream", amount: "for serving", dept: "Dairy" },
      { item: "Shredded Mexican cheese", amount: "1 cup", dept: "Dairy", search: "shredded mexican blend cheese" },
    ],
    steps: [
      "Toss sliced chicken with fajita seasoning.",
      "Sear chicken in a hot skillet with oil, 5–6 minutes; remove.",
      "Sauté peppers and onion until charred at the edges, 6–8 minutes.",
      "Return chicken, squeeze lime over everything, and toss.",
      "Serve in warm tortillas with sour cream and cheese.",
    ],
  },
  {
    id: "creamy-tuscan-pasta",
    calories: 790,
    health: "indulgent",
    allergens: ["dairy", "gluten"],
    name: "Creamy Tuscan Chicken Pasta",
    time: 35,
    tags: ["Italian", "Comfort"],
    ingredients: [
      { item: "Penne pasta", amount: "8 oz", dept: "Pantry", search: "penne pasta" },
      { item: "Chicken breasts", amount: "1 lb, cubed", dept: "Meat", search: "boneless chicken breast" },
      { item: "Heavy cream", amount: "1 cup", dept: "Dairy" },
      { item: "Sun-dried tomatoes", amount: "1/2 cup", dept: "Pantry", search: "sun dried tomatoes" },
      { item: "Baby spinach", amount: "3 cups", dept: "Produce" },
      { item: "Parmesan cheese", amount: "1/2 cup, grated", dept: "Dairy", search: "grated parmesan cheese" },
      { item: "Garlic", amount: "4 cloves", dept: "Produce" },
      { item: "Italian seasoning", amount: "1 tsp", dept: "Spices" },
    ],
    steps: [
      "Cook penne per package directions; reserve 1/2 cup pasta water.",
      "Season and sear cubed chicken until golden; remove.",
      "Sauté garlic and sun-dried tomatoes 1 minute, then add cream and Italian seasoning.",
      "Stir in parmesan until melted, then wilt in the spinach.",
      "Toss with pasta and chicken, loosening with pasta water as needed.",
    ],
  },
  {
    id: "sheet-pan-sausage",
    calories: 620,
    health: "balanced",
    allergens: [],
    name: "Sheet Pan Sausage & Veggies",
    time: 35,
    tags: ["One Pan", "Easy Cleanup"],
    ingredients: [
      { item: "Smoked sausage", amount: "14 oz, sliced", dept: "Meat", search: "smoked sausage" },
      { item: "Baby potatoes", amount: "1 lb, halved", dept: "Produce", search: "baby gold potatoes" },
      { item: "Broccoli", amount: "1 head, in florets", dept: "Produce", search: "broccoli crowns" },
      { item: "Red onion", amount: "1, in wedges", dept: "Produce" },
      { item: "Olive oil", amount: "3 tbsp", dept: "Pantry" },
      { item: "Smoked paprika", amount: "1 tsp", dept: "Spices" },
      { item: "Garlic powder", amount: "1 tsp", dept: "Spices" },
    ],
    steps: [
      "Preheat oven to 425°F.",
      "Toss potatoes with oil and spices; roast 15 minutes alone.",
      "Add sausage, broccoli, and onion tossed with remaining oil.",
      "Roast 15–20 more minutes until potatoes are tender and edges crisp.",
    ],
  },
  {
    id: "honey-garlic-shrimp",
    calories: 540,
    health: "balanced",
    allergens: ["shellfish", "soy"],
    name: "Honey Garlic Shrimp Stir-Fry",
    time: 20,
    tags: ["Seafood", "Quick", "Asian"],
    ingredients: [
      { item: "Large shrimp", amount: "1 lb, peeled", dept: "Seafood", search: "raw shrimp peeled" },
      { item: "Honey", amount: "1/4 cup", dept: "Pantry" },
      { item: "Soy sauce", amount: "1/4 cup", dept: "International", search: "soy sauce" },
      { item: "Garlic", amount: "4 cloves", dept: "Produce" },
      { item: "Fresh ginger", amount: "1 tbsp, grated", dept: "Produce", search: "fresh ginger root" },
      { item: "Snow peas", amount: "2 cups", dept: "Produce" },
      { item: "Jasmine rice", amount: "1 cup, uncooked", dept: "International", search: "jasmine rice" },
      { item: "Green onions", amount: "2, sliced", dept: "Produce" },
    ],
    steps: [
      "Start rice per package directions.",
      "Whisk honey, soy sauce, garlic, and ginger into a sauce.",
      "Sear shrimp 1–2 minutes per side in a hot pan; remove.",
      "Stir-fry snow peas 2 minutes, add sauce and simmer until glossy.",
      "Return shrimp to coat, then serve over rice with green onions.",
    ],
  },
  {
    id: "turkey-burgers",
    griddle: true,
    calories: 730,
    health: "balanced",
    allergens: ["dairy", "gluten", "eggs"],
    name: "Juicy Turkey Burgers",
    time: 25,
    tags: ["American", "Grill"],
    ingredients: [
      { item: "Ground turkey", amount: "1 lb", dept: "Meat", search: "93% lean ground turkey" },
      { item: "Brioche buns", amount: "2", dept: "Bakery", search: "brioche hamburger buns" },
      { item: "Cheddar cheese slices", amount: "2", dept: "Dairy", search: "sliced cheddar cheese" },
      { item: "Tomato", amount: "1, sliced", dept: "Produce", search: "tomatoes on the vine" },
      { item: "Romaine lettuce", amount: "2 leaves", dept: "Produce", search: "romaine lettuce" },
      { item: "Red onion", amount: "1/2, sliced", dept: "Produce" },
      { item: "Worcestershire sauce", amount: "1 tbsp", dept: "Pantry" },
      { item: "Mayonnaise", amount: "for serving", dept: "Pantry" },
      { item: "Sweet potato fries", amount: "1 bag", dept: "Frozen", search: "frozen sweet potato fries" },
    ],
    steps: [
      "Bake sweet potato fries per the bag while you cook.",
      "Mix turkey with Worcestershire, salt, and pepper; form 2 patties with a thumb dimple.",
      "Cook 4–5 minutes per side to 165°F, adding cheddar in the last minute.",
      "Toast buns, then build with mayo, lettuce, tomato, and onion.",
    ],
  },
  {
    id: "veggie-stir-fry-noodles",
    calories: 490,
    health: "healthy",
    allergens: ["gluten", "soy", "eggs"],
    name: "Veggie Lo Mein Night",
    time: 25,
    tags: ["Vegetarian", "Asian", "Quick"],
    ingredients: [
      { item: "Lo mein noodles", amount: "8 oz", dept: "International", search: "lo mein noodles" },
      { item: "Broccoli", amount: "2 cups florets", dept: "Produce", search: "broccoli crowns" },
      { item: "Carrots", amount: "2, julienned", dept: "Produce" },
      { item: "Mushrooms", amount: "8 oz, sliced", dept: "Produce", search: "baby bella mushrooms" },
      { item: "Soy sauce", amount: "3 tbsp", dept: "International", search: "soy sauce" },
      { item: "Sesame oil", amount: "1 tbsp", dept: "International", search: "toasted sesame oil" },
      { item: "Garlic", amount: "3 cloves", dept: "Produce" },
      { item: "Eggs", amount: "2", dept: "Dairy", search: "large eggs" },
    ],
    steps: [
      "Boil noodles per package; drain and toss with a little sesame oil.",
      "Scramble eggs in the wok; set aside.",
      "Stir-fry mushrooms, broccoli, and carrots with garlic until crisp-tender.",
      "Add noodles, soy sauce, and sesame oil; toss over high heat.",
      "Fold in the eggs and serve hot.",
    ],
  },
  {
    id: "slow-cooker-chili",
    calories: 740,
    health: "indulgent",
    allergens: ["dairy", "gluten"],
    name: "Cozy Beef Chili",
    time: 45,
    tags: ["Comfort", "Make Ahead"],
    ingredients: [
      { item: "Ground beef", amount: "1 lb", dept: "Meat", search: "ground beef 80/20" },
      { item: "Kidney beans", amount: "1 can (15 oz)", dept: "Pantry", search: "canned kidney beans" },
      { item: "Black beans", amount: "1 can (15 oz)", dept: "Pantry", search: "canned black beans" },
      { item: "Crushed tomatoes", amount: "1 can (28 oz)", dept: "Pantry", search: "canned crushed tomatoes" },
      { item: "Yellow onion", amount: "1, diced", dept: "Produce" },
      { item: "Chili powder", amount: "2 tbsp", dept: "Spices" },
      { item: "Cumin", amount: "1 tbsp", dept: "Spices", search: "ground cumin" },
      { item: "Shredded cheddar", amount: "for topping", dept: "Dairy", search: "shredded cheddar cheese" },
      { item: "Cornbread mix", amount: "1 box", dept: "Pantry", search: "cornbread mix" },
    ],
    steps: [
      "Brown beef with onion; drain excess fat.",
      "Add spices and toast 1 minute, then add tomatoes and drained beans.",
      "Simmer at least 30 minutes (longer is better), stirring occasionally.",
      "Bake cornbread per the box while the chili simmers.",
      "Serve topped with shredded cheddar.",
    ],
  },
  {
    id: "caprese-chicken",
    calories: 450,
    health: "healthy",
    allergens: ["dairy"],
    name: "Caprese Chicken",
    time: 30,
    tags: ["Italian", "Light"],
    ingredients: [
      { item: "Chicken breasts", amount: "2", dept: "Meat", search: "boneless chicken breast" },
      { item: "Fresh mozzarella", amount: "4 oz, sliced", dept: "Deli", search: "fresh mozzarella" },
      { item: "Tomatoes", amount: "2, sliced", dept: "Produce", search: "tomatoes on the vine" },
      { item: "Fresh basil", amount: "1 bunch", dept: "Produce" },
      { item: "Balsamic glaze", amount: "2 tbsp", dept: "Pantry", search: "balsamic glaze" },
      { item: "Green beans", amount: "12 oz", dept: "Produce", search: "fresh green beans" },
      { item: "Olive oil", amount: "2 tbsp", dept: "Pantry" },
    ],
    steps: [
      "Season chicken and sear in olive oil 5–6 minutes per side until cooked through.",
      "Top each breast with tomato and mozzarella; cover until cheese melts.",
      "Steam green beans 4–5 minutes until crisp-tender.",
      "Plate, drizzle with balsamic glaze, and shower with torn basil.",
    ],
  },
  {
    id: "shrimp-tacos",
    griddle: true,
    calories: 510,
    health: "healthy",
    allergens: ["shellfish", "dairy"],
    name: "Blackened Shrimp Tacos",
    time: 25,
    tags: ["Seafood", "Mexican", "Quick"],
    ingredients: [
      { item: "Large shrimp", amount: "1 lb, peeled", dept: "Seafood", search: "raw shrimp peeled" },
      { item: "Corn tortillas", amount: "8 small", dept: "International", search: "corn tortillas" },
      { item: "Coleslaw mix", amount: "1 bag", dept: "Produce", search: "coleslaw mix" },
      { item: "Avocado", amount: "1", dept: "Produce" },
      { item: "Lime", amount: "2", dept: "Produce" },
      { item: "Cilantro", amount: "1/2 bunch", dept: "Produce", search: "fresh cilantro" },
      { item: "Blackened seasoning", amount: "2 tbsp", dept: "Spices" },
      { item: "Sour cream", amount: "1/2 cup", dept: "Dairy" },
    ],
    steps: [
      "Toss slaw mix with lime juice, half the cilantro, and a pinch of salt.",
      "Stir sour cream with lime juice into a quick crema.",
      "Coat shrimp in blackened seasoning and sear 1–2 minutes per side.",
      "Warm tortillas, then build: slaw, shrimp, avocado, crema, cilantro.",
    ],
  },
  {
    id: "baked-ziti",
    calories: 860,
    health: "indulgent",
    allergens: ["dairy", "gluten"],
    name: "Weeknight Baked Ziti",
    time: 45,
    tags: ["Italian", "Comfort", "Leftovers"],
    ingredients: [
      { item: "Ziti pasta", amount: "12 oz", dept: "Pantry", search: "ziti pasta" },
      { item: "Italian sausage", amount: "1 lb", dept: "Meat", search: "ground italian sausage" },
      { item: "Marinara sauce", amount: "1 jar (24 oz)", dept: "Pantry", search: "marinara sauce" },
      { item: "Ricotta cheese", amount: "1 cup", dept: "Dairy", search: "ricotta cheese" },
      { item: "Shredded mozzarella", amount: "2 cups", dept: "Dairy", search: "shredded mozzarella" },
      { item: "Parmesan cheese", amount: "1/2 cup", dept: "Dairy", search: "grated parmesan cheese" },
      { item: "Garlic bread", amount: "1 loaf", dept: "Frozen", search: "frozen garlic bread" },
    ],
    steps: [
      "Preheat oven to 375°F. Boil ziti 2 minutes shy of al dente.",
      "Brown sausage, then stir in marinara.",
      "Toss pasta with sauce and dollops of ricotta in a baking dish.",
      "Top with mozzarella and parmesan; bake 20 minutes until bubbly.",
      "Bake garlic bread alongside for the last 10 minutes.",
    ],
  },
  {
    id: "greek-chicken-bowls",
    calories: 560,
    health: "healthy",
    allergens: ["dairy", "gluten"],
    name: "Greek Chicken Bowls",
    time: 30,
    tags: ["Mediterranean", "Healthy"],
    ingredients: [
      { item: "Chicken thighs", amount: "1 lb, boneless", dept: "Meat", search: "boneless chicken thighs" },
      { item: "Cucumber", amount: "1, diced", dept: "Produce" },
      { item: "Cherry tomatoes", amount: "1 pint", dept: "Produce" },
      { item: "Red onion", amount: "1/2, diced", dept: "Produce" },
      { item: "Feta cheese", amount: "1/2 cup, crumbled", dept: "Dairy", search: "crumbled feta cheese" },
      { item: "Kalamata olives", amount: "1/2 cup", dept: "Deli", search: "kalamata olives" },
      { item: "Tzatziki", amount: "1/2 cup", dept: "Deli", search: "tzatziki" },
      { item: "Couscous", amount: "1 cup, uncooked", dept: "Pantry", search: "pearl couscous" },
      { item: "Dried oregano", amount: "1 tbsp", dept: "Spices" },
      { item: "Lemon", amount: "1", dept: "Produce" },
    ],
    steps: [
      "Marinate chicken in olive oil, lemon juice, oregano, salt, and pepper (10+ minutes).",
      "Cook couscous per package directions.",
      "Sear chicken 5–6 minutes per side; rest, then slice.",
      "Build bowls: couscous, chicken, cucumber, tomatoes, onion, olives, feta.",
      "Finish with tzatziki and a squeeze of lemon.",
    ],
  },
  {
    id: "pork-chops-apples",
    calories: 680,
    health: "balanced",
    allergens: ["dairy"],
    name: "Skillet Pork Chops & Apples",
    time: 30,
    tags: ["American", "Fall Favorite"],
    ingredients: [
      { item: "Pork chops", amount: "2 bone-in", dept: "Meat", search: "bone-in pork chops" },
      { item: "Honeycrisp apples", amount: "2, sliced", dept: "Produce", search: "honeycrisp apples" },
      { item: "Yellow onion", amount: "1, sliced", dept: "Produce" },
      { item: "Butter", amount: "2 tbsp", dept: "Dairy", search: "unsalted butter" },
      { item: "Fresh thyme", amount: "4 sprigs", dept: "Produce", search: "fresh thyme" },
      { item: "Apple cider", amount: "1/2 cup", dept: "Pantry", search: "apple cider" },
      { item: "Mashed potatoes", amount: "1 package", dept: "Dairy", search: "refrigerated mashed potatoes" },
    ],
    steps: [
      "Season chops and sear in butter 4–5 minutes per side; remove to rest.",
      "Sauté apples and onion in the same skillet until soft and golden.",
      "Deglaze with apple cider, add thyme, and simmer to a glaze.",
      "Heat mashed potatoes; serve chops over them, smothered in apples.",
    ],
  },
  {
    id: "margherita-flatbreads",
    calories: 620,
    health: "balanced",
    allergens: ["dairy", "gluten"],
    name: "Margherita Flatbreads & Salad",
    time: 20,
    tags: ["Vegetarian", "Quick", "Date Night"],
    ingredients: [
      { item: "Naan or flatbreads", amount: "2", dept: "Bakery", search: "naan bread" },
      { item: "Marinara sauce", amount: "1/2 cup", dept: "Pantry", search: "pizza sauce" },
      { item: "Fresh mozzarella", amount: "8 oz", dept: "Deli", search: "fresh mozzarella" },
      { item: "Fresh basil", amount: "1 bunch", dept: "Produce" },
      { item: "Spring mix", amount: "1 bag", dept: "Produce", search: "spring mix salad" },
      { item: "Balsamic vinaigrette", amount: "1/4 cup", dept: "Pantry", search: "balsamic vinaigrette" },
      { item: "Cherry tomatoes", amount: "1 cup", dept: "Produce" },
    ],
    steps: [
      "Preheat oven to 450°F.",
      "Top flatbreads with sauce, torn mozzarella, and halved cherry tomatoes.",
      "Bake 8–10 minutes until cheese bubbles and edges crisp.",
      "Toss spring mix with vinaigrette.",
      "Scatter basil over the flatbreads, slice, and serve with salad.",
    ],
  },
  {
    id: "blackstone-smash-burgers",
    griddle: true,
    calories: 900,
    health: "indulgent",
    allergens: ["gluten", "dairy"],
    name: "Blackstone Smash Burgers",
    time: 25,
    tags: ["Blackstone", "Comfort"],
    ingredients: [
      { item: "Ground beef", amount: "1 lb (80/20)", dept: "Meat", search: "ground beef 80/20" },
      { item: "American cheese slices", amount: "4", dept: "Dairy", search: "american cheese slices" },
      { item: "Brioche buns", amount: "2", dept: "Bakery", search: "brioche hamburger buns" },
      { item: "Yellow onion", amount: "1, sliced paper thin", dept: "Produce" },
      { item: "Dill pickle chips", amount: "1/2 cup", dept: "Pantry", search: "dill pickle chips" },
      { item: "Mayonnaise", amount: "3 tbsp", dept: "Pantry" },
      { item: "Yellow mustard", amount: "1 tbsp", dept: "Pantry", search: "yellow mustard" },
    ],
    steps: [
      "Heat the griddle to high. Divide the beef into 4 loose 4-oz balls — do not pack them.",
      "Drop the balls on the hot griddle, top each with a pile of thin onion, and smash hard with a spatula or press until very thin.",
      "Season with salt and pepper; cook 2 minutes until the edges are lacy and crisp.",
      "Scrape, flip, add a cheese slice to each patty, and stack into doubles.",
      "Toast the buns on the griddle; build with mayo-mustard sauce and pickles.",
    ],
  },
  {
    id: "blackstone-hibachi-chicken",
    griddle: true,
    calories: 760,
    health: "balanced",
    allergens: ["soy", "eggs"],
    name: "Hibachi Chicken & Fried Rice",
    time: 35,
    tags: ["Blackstone", "Asian"],
    ingredients: [
      { item: "Chicken breasts", amount: "1 lb, cubed", dept: "Meat", search: "boneless chicken breast" },
      { item: "Cooked rice", amount: "3 cups, day-old", dept: "International", search: "jasmine rice" },
      { item: "Eggs", amount: "2", dept: "Dairy", search: "large eggs" },
      { item: "Soy sauce", amount: "1/4 cup", dept: "International", search: "soy sauce" },
      { item: "Butter", amount: "4 tbsp", dept: "Dairy", search: "unsalted butter" },
      { item: "Zucchini", amount: "1, diced", dept: "Produce" },
      { item: "Yellow onion", amount: "1, diced", dept: "Produce" },
      { item: "Garlic", amount: "4 cloves", dept: "Produce" },
      { item: "Yum yum sauce", amount: "for serving", dept: "Pantry", search: "yum yum sauce" },
    ],
    steps: [
      "Heat one zone of the griddle to high and one to medium.",
      "Sear the chicken with butter, salt, and pepper on the hot zone, tossing hibachi-style, 6–8 minutes; splash with soy sauce.",
      "On the medium zone, sauté the onion, zucchini, and garlic in butter.",
      "Push everything aside; scramble the eggs, then fold in the cold rice, butter, and soy sauce, pressing flat to crisp.",
      "Plate chicken over fried rice with vegetables and a drizzle of yum yum sauce.",
    ],
  },
  {
    id: "blackstone-philly-cheesesteak",
    griddle: true,
    calories: 850,
    health: "indulgent",
    allergens: ["gluten", "dairy"],
    name: "Philly Cheesesteaks",
    time: 30,
    tags: ["Blackstone", "Comfort"],
    ingredients: [
      { item: "Ribeye steak", amount: "1 lb, shaved or very thin", dept: "Meat", search: "shaved beef steak" },
      { item: "Hoagie rolls", amount: "2", dept: "Bakery", search: "hoagie rolls" },
      { item: "Provolone cheese", amount: "6 slices", dept: "Deli", search: "sliced provolone" },
      { item: "Green bell pepper", amount: "1, sliced", dept: "Produce", search: "green bell pepper" },
      { item: "Yellow onion", amount: "1, sliced", dept: "Produce" },
      { item: "Butter", amount: "2 tbsp", dept: "Dairy", search: "unsalted butter" },
    ],
    steps: [
      "Heat the griddle to medium-high. Sauté the peppers and onions in butter until soft and browned; slide to the cool side.",
      "Crank the heat, then sear the shaved beef, chopping and flipping with two spatulas, 3–4 minutes.",
      "Season, combine the beef with the peppers and onions, and divide into two sandwich-shaped piles.",
      "Lay provolone over each pile and let it melt.",
      "Butter and toast the rolls on the griddle, then scoop each pile straight into a roll.",
    ],
  },
  {
    id: "blackstone-smash-tacos",
    griddle: true,
    calories: 820,
    health: "indulgent",
    allergens: ["gluten", "dairy", "eggs"],
    name: "Big Mac Smash Tacos",
    time: 25,
    tags: ["Blackstone", "Viral"],
    ingredients: [
      { item: "Ground beef", amount: "1 lb", dept: "Meat", search: "ground beef 80/20" },
      { item: "Flour tortillas", amount: "6 small", dept: "International", search: "flour tortillas" },
      { item: "American cheese slices", amount: "6", dept: "Dairy", search: "american cheese slices" },
      { item: "Shredded lettuce", amount: "2 cups", dept: "Produce", search: "shredded lettuce" },
      { item: "Dill pickle chips", amount: "1/2 cup", dept: "Pantry", search: "dill pickle chips" },
      { item: "Thousand island dressing", amount: "1/3 cup", dept: "Pantry", search: "thousand island dressing" },
      { item: "White onion", amount: "1/2, minced", dept: "Produce", search: "white onion" },
    ],
    steps: [
      "Heat the griddle to high. Form 6 small beef balls (about 2.5 oz each).",
      "Press one ball thin onto each tortilla so the beef covers it edge to edge.",
      "Lay the tacos beef-side down on the griddle and smash; cook 2–3 minutes until deeply browned.",
      "Flip, top each with a cheese slice, and cook 1 more minute until melted.",
      "Top with dressing, lettuce, pickles, and minced onion; fold and eat immediately.",
    ],
  },
  {
    id: "blackstone-street-tacos",
    griddle: true,
    calories: 620,
    health: "balanced",
    allergens: [],
    name: "Carne Asada Street Tacos",
    time: 30,
    tags: ["Blackstone", "Mexican"],
    ingredients: [
      { item: "Skirt steak", amount: "1 lb", dept: "Meat", search: "skirt steak" },
      { item: "Corn tortillas", amount: "8 street-size", dept: "International", search: "street taco corn tortillas" },
      { item: "Limes", amount: "3", dept: "Produce", search: "limes" },
      { item: "Orange", amount: "1 (for the marinade)", dept: "Produce", search: "navel oranges" },
      { item: "Cilantro", amount: "1 bunch", dept: "Produce", search: "fresh cilantro" },
      { item: "White onion", amount: "1, minced", dept: "Produce", search: "white onion" },
      { item: "Garlic", amount: "4 cloves", dept: "Produce" },
      { item: "Cumin", amount: "2 tsp", dept: "Spices", search: "ground cumin" },
    ],
    steps: [
      "Marinate the steak in orange juice, lime juice, garlic, cumin, salt, and half the cilantro (30 minutes if you can).",
      "Heat the griddle to high; sear the steak 3–4 minutes per side for medium.",
      "Rest 5 minutes, then chop into small pieces, crisping the bits briefly back on the griddle.",
      "Warm the tortillas on the griddle, doubling them up street-style.",
      "Fill with steak, minced onion, cilantro, and a squeeze of lime.",
    ],
  },
  {
    id: "blackstone-quesadillas",
    griddle: true,
    calories: 780,
    health: "indulgent",
    allergens: ["gluten", "dairy"],
    name: "Crispy Chicken Quesadillas",
    time: 25,
    tags: ["Blackstone", "Mexican"],
    ingredients: [
      { item: "Chicken breasts", amount: "1 lb, diced", dept: "Meat", search: "boneless chicken breast" },
      { item: "Flour tortillas", amount: "4 large", dept: "International", search: "flour tortillas burrito size" },
      { item: "Shredded Mexican cheese", amount: "2 cups", dept: "Dairy", search: "shredded mexican blend cheese" },
      { item: "Taco seasoning", amount: "2 tbsp", dept: "Spices", search: "taco seasoning" },
      { item: "Bell pepper", amount: "1, diced", dept: "Produce", search: "bell pepper" },
      { item: "Sour cream", amount: "for serving", dept: "Dairy" },
      { item: "Salsa", amount: "for serving", dept: "Pantry", search: "salsa" },
    ],
    steps: [
      "Heat the griddle to medium-high. Cook the chicken with taco seasoning and the diced pepper, 6–8 minutes; set aside.",
      "Wipe a zone, lay down the tortillas, and cover half of each with cheese, chicken, and more cheese.",
      "Fold and press with a spatula; cook 2–3 minutes per side until shatteringly crisp and golden.",
      "Rest 2 minutes, slice into wedges, and serve with sour cream and salsa.",
    ],
  },
  {
    id: "blackstone-steak-potatoes",
    griddle: true,
    calories: 830,
    health: "indulgent",
    allergens: ["dairy"],
    name: "Garlic Butter Steak & Smashed Potatoes",
    time: 35,
    tags: ["Blackstone", "Date Night"],
    ingredients: [
      { item: "Sirloin steaks", amount: "2 (8 oz each)", dept: "Meat", search: "sirloin steak" },
      { item: "Baby potatoes", amount: "1 lb, boiled until tender", dept: "Produce", search: "baby gold potatoes" },
      { item: "Butter", amount: "4 tbsp", dept: "Dairy", search: "unsalted butter" },
      { item: "Garlic", amount: "6 cloves", dept: "Produce" },
      { item: "Fresh rosemary", amount: "2 sprigs", dept: "Produce", search: "fresh rosemary" },
      { item: "Asparagus", amount: "1 bunch", dept: "Produce" },
    ],
    steps: [
      "Boil the potatoes ahead (or microwave 6–8 minutes until tender). Heat the griddle to high.",
      "Smash each potato flat on the oiled griddle and crisp 4–5 minutes per side with salt.",
      "Sear the steaks 3–4 minutes per side, basting with garlic-rosemary butter at the end; rest 5 minutes.",
      "Sear the asparagus in the steak butter while the steaks rest.",
      "Slice the steaks and serve over the crispy potatoes with the asparagus.",
    ],
  },
  {
    id: "blackstone-cowboy-hash",
    griddle: true,
    calories: 700,
    health: "balanced",
    allergens: [],
    name: "Cowboy Sausage Hash",
    time: 30,
    tags: ["Blackstone", "One Surface"],
    ingredients: [
      { item: "Smoked sausage", amount: "14 oz, sliced", dept: "Meat", search: "smoked sausage" },
      { item: "Baby potatoes", amount: "1 lb, diced small", dept: "Produce", search: "baby gold potatoes" },
      { item: "Zucchini", amount: "1, diced", dept: "Produce" },
      { item: "Bell peppers", amount: "2, diced", dept: "Produce", search: "bell pepper" },
      { item: "Yellow onion", amount: "1, diced", dept: "Produce" },
      { item: "Smoked paprika", amount: "2 tsp", dept: "Spices" },
      { item: "Olive oil", amount: "3 tbsp", dept: "Pantry" },
    ],
    steps: [
      "Heat the griddle to medium-high. Toss the diced potatoes in oil, salt, and paprika; cook 12–15 minutes, flipping occasionally, until golden.",
      "Add the sausage and let it brown against the steel, 4–5 minutes.",
      "Add the peppers, onion, and zucchini; toss everything together.",
      "Cook 5 more minutes until the vegetables are charred at the edges. Season and serve straight off the griddle.",
    ],
  },
  {
    id: "blackstone-cuban-sandwiches",
    griddle: true,
    calories: 860,
    health: "indulgent",
    allergens: ["gluten", "dairy"],
    name: "Griddle-Pressed Cuban Sandwiches",
    time: 30,
    tags: ["Blackstone", "Florida Classic"],
    ingredients: [
      { item: "Cuban bread or hoagies", amount: "2", dept: "Bakery", search: "cuban bread" },
      { item: "Roast pork", amount: "1/2 lb, sliced", dept: "Deli", search: "pork tenderloin" },
      { item: "Ham", amount: "1/2 lb, sliced", dept: "Deli", search: "sliced ham" },
      { item: "Swiss cheese", amount: "4 slices", dept: "Deli", search: "sliced swiss cheese" },
      { item: "Dill pickle chips", amount: "1/2 cup", dept: "Pantry", search: "dill pickle chips" },
      { item: "Yellow mustard", amount: "2 tbsp", dept: "Pantry", search: "yellow mustard" },
      { item: "Butter", amount: "2 tbsp", dept: "Dairy", search: "unsalted butter" },
    ],
    steps: [
      "Heat the griddle to medium. Warm the pork and ham briefly on the steel.",
      "Build the sandwiches: mustard, ham, pork, swiss, pickles.",
      "Butter the outsides, place on the griddle, and press hard with a burger press or a foil-wrapped brick.",
      "Cook 3–4 minutes per side, pressing, until flat, crusty, and the cheese is molten. Slice diagonally.",
    ],
  },
  {
    id: "blackstone-bulgogi-bowls",
    griddle: true,
    calories: 720,
    health: "balanced",
    allergens: ["soy"],
    name: "Korean Beef Bulgogi Bowls",
    time: 30,
    tags: ["Blackstone", "Asian"],
    ingredients: [
      { item: "Ribeye or sirloin", amount: "1 lb, sliced paper thin", dept: "Meat", search: "shaved beef steak" },
      { item: "Soy sauce", amount: "1/4 cup", dept: "International", search: "soy sauce" },
      { item: "Brown sugar", amount: "2 tbsp", dept: "Pantry", search: "brown sugar" },
      { item: "Sesame oil", amount: "1 tbsp", dept: "International", search: "toasted sesame oil" },
      { item: "Garlic", amount: "5 cloves", dept: "Produce" },
      { item: "Jasmine rice", amount: "1 cup, uncooked", dept: "International", search: "jasmine rice" },
      { item: "Cucumber", amount: "1, thinly sliced", dept: "Produce" },
      { item: "Green onions", amount: "3, sliced", dept: "Produce" },
      { item: "Sesame seeds", amount: "1 tbsp", dept: "Spices", search: "sesame seeds" },
    ],
    steps: [
      "Marinate the thin-sliced beef in soy sauce, brown sugar, sesame oil, and garlic (15+ minutes). Start the rice.",
      "Heat the griddle to high until it just smokes.",
      "Sear the beef in a single layer, undisturbed 1–2 minutes, then flip and char the other side.",
      "Build bowls: rice, beef, cucumber, green onions, and a shower of sesame seeds.",
    ],
  },
  {
    id: "loaded-bacon-mac",
    calories: 950,
    health: "indulgent",
    allergens: ["dairy", "gluten"],
    name: "Loaded Bacon Mac & Cheese",
    time: 40,
    tags: ["Comfort", "Crowd Pleaser"],
    ingredients: [
      { item: "Cavatappi pasta", amount: "12 oz", dept: "Pantry", search: "cavatappi pasta" },
      { item: "Bacon", amount: "8 slices", dept: "Meat", search: "thick cut bacon" },
      { item: "Sharp cheddar", amount: "2 cups, shredded", dept: "Dairy", search: "sharp cheddar block" },
      { item: "Monterey jack", amount: "1 cup, shredded", dept: "Dairy", search: "monterey jack cheese" },
      { item: "Whole milk", amount: "2 cups", dept: "Dairy" },
      { item: "Butter", amount: "3 tbsp", dept: "Dairy", search: "unsalted butter" },
      { item: "All-purpose flour", amount: "3 tbsp", dept: "Pantry" },
      { item: "Panko breadcrumbs", amount: "1/2 cup", dept: "Pantry", search: "panko breadcrumbs" },
      { item: "Green onions", amount: "2, sliced", dept: "Produce" },
    ],
    steps: [
      "Cook pasta 2 minutes shy of al dente; drain.",
      "Crisp the bacon; crumble and reserve, keeping 1 tbsp of the fat.",
      "Melt butter with the bacon fat, whisk in flour 1 minute, then slowly whisk in milk until thickened.",
      "Off heat, stir in cheeses until smooth; fold in pasta and half the bacon.",
      "Top with panko and remaining bacon; broil 2–3 minutes until golden. Finish with green onions.",
    ],
  },
  {
    id: "buffalo-chicken-sandwiches",
    calories: 880,
    health: "indulgent",
    allergens: ["dairy", "gluten", "eggs"],
    name: "Crispy Buffalo Chicken Sandwiches",
    time: 35,
    tags: ["Comfort", "Weekend"],
    ingredients: [
      { item: "Chicken breasts", amount: "2, halved flat", dept: "Meat", search: "boneless chicken breast" },
      { item: "Buttermilk", amount: "1 cup", dept: "Dairy" },
      { item: "All-purpose flour", amount: "1 cup", dept: "Pantry" },
      { item: "Buffalo sauce", amount: "1/2 cup", dept: "Pantry", search: "franks redhot buffalo sauce" },
      { item: "Brioche buns", amount: "2", dept: "Bakery", search: "brioche hamburger buns" },
      { item: "Blue cheese dressing", amount: "1/4 cup", dept: "Pantry", search: "blue cheese dressing" },
      { item: "Dill pickle chips", amount: "1/2 cup", dept: "Pantry", search: "dill pickle chips" },
      { item: "Shredded lettuce", amount: "1 cup", dept: "Produce", search: "shredded lettuce" },
      { item: "Vegetable oil", amount: "for frying", dept: "Pantry", search: "vegetable oil" },
    ],
    steps: [
      "Soak chicken in buttermilk with salt and pepper, 15+ minutes.",
      "Dredge in seasoned flour, pressing so it sticks.",
      "Shallow-fry in 1/2 inch of oil, 4–5 minutes per side, to 165°F.",
      "Toss the hot chicken in buffalo sauce.",
      "Build on toasted buns with blue cheese dressing, pickles, and lettuce.",
    ],
  },
];
