// ============================================================
// RECIPE DATA
// Add your own recipes here! Each recipe needs:
//   id        - unique string
//   name      - display name
//   emoji     - shown on the card
//   time      - total cook time in minutes
//   tags      - array of labels shown on the card
//   steps     - array of instruction strings
//   ingredients - array of { item, amount, dept, search }
//     item   - display name of the ingredient
//     amount - quantity (recipes are portioned for two)
//     dept   - Publix department (must match a key in DEPARTMENTS below)
//     search - (optional) term used for the Publix link; defaults to item
// ============================================================

// Common allergens used for filtering. Each recipe lists which of
// these it contains in its `allergens` array (use the lowercase keys).
const ALLERGENS = {
  shellfish: { label: "Shellfish", emoji: "🦐" },
  nuts:      { label: "Nuts",      emoji: "🥜" },
  fish:      { label: "Fish",      emoji: "🐟" },
  dairy:     { label: "Dairy",     emoji: "🥛" },
  gluten:    { label: "Gluten",    emoji: "🌾" },
  eggs:      { label: "Eggs",      emoji: "🥚" },
  soy:       { label: "Soy",       emoji: "🫘" },
};

// Departments in roughly the order you'd walk a Publix,
// used to group/sort the weekly shopping list.
const DEPARTMENTS = {
  "Produce":        { emoji: "🥬", order: 1 },
  "Bakery":         { emoji: "🥖", order: 2 },
  "Deli":           { emoji: "🥪", order: 3 },
  "Meat":           { emoji: "🥩", order: 4 },
  "Seafood":        { emoji: "🐟", order: 5 },
  "Dairy":          { emoji: "🥛", order: 6 },
  "Frozen":         { emoji: "🧊", order: 7 },
  "Pantry":         { emoji: "🥫", order: 8 },
  "Spices":         { emoji: "🧂", order: 9 },
  "International":  { emoji: "🌎", order: 10 },
};

const RECIPES = [
  {
    id: "lemon-garlic-salmon",
    allergens: ["fish", "dairy"],
    name: "Lemon Garlic Butter Salmon",
    emoji: "🐟",
    time: 25,
    tags: ["Seafood", "One Pan", "Light"],
    ingredients: [
      { item: "Salmon fillets", amount: "2 (6 oz each)", dept: "Seafood", search: "fresh salmon fillet" },
      { item: "Asparagus", amount: "1 bunch", dept: "Produce" },
      { item: "Lemon", amount: "1", dept: "Produce" },
      { item: "Garlic", amount: "3 cloves", dept: "Produce" },
      { item: "Butter", amount: "3 tbsp", dept: "Dairy", search: "unsalted butter" },
      { item: "Fresh parsley", amount: "2 tbsp, chopped", dept: "Produce" },
      { item: "Olive oil", amount: "1 tbsp", dept: "Pantry" },
    ],
    steps: [
      "Preheat oven to 400°F. Line a sheet pan with foil.",
      "Toss asparagus with olive oil, salt, and pepper; arrange on one side of the pan.",
      "Place salmon on the other side. Melt butter with minced garlic and pour over the salmon.",
      "Top with lemon slices and bake 12–15 minutes until salmon flakes easily.",
      "Finish with chopped parsley and a squeeze of lemon.",
    ],
  },
  {
    id: "chicken-fajita-skillet",
    allergens: ["dairy", "gluten"],
    name: "Chicken Fajita Skillet",
    emoji: "🌮",
    time: 30,
    tags: ["Mexican", "One Pan"],
    ingredients: [
      { item: "Chicken breasts", amount: "1 lb, sliced", dept: "Meat", search: "boneless chicken breast" },
      { item: "Bell peppers", amount: "2 (any color)", dept: "Produce", search: "bell pepper" },
      { item: "Yellow onion", amount: "1, sliced", dept: "Produce" },
      { item: "Fajita seasoning", amount: "2 tbsp", dept: "Spices" },
      { item: "Flour tortillas", amount: "6 small", dept: "International", search: "flour tortillas" },
      { item: "Lime", amount: "1", dept: "Produce" },
      { item: "Sour cream", amount: "for serving", dept: "Dairy" },
      { item: "Shredded Mexican cheese", amount: "1 cup", dept: "Dairy", search: "shredded mexican blend cheese" },
    ],
    steps: [
      "Toss sliced chicken with fajita seasoning.",
      "Sear chicken in a hot skillet with oil, 5–6 minutes; remove.",
      "Sauté peppers and onion until charred at the edges, 6–8 minutes.",
      "Return chicken, squeeze lime over everything, and toss.",
      "Serve in warm tortillas with sour cream and cheese.",
    ],
  },
  {
    id: "creamy-tuscan-pasta",
    allergens: ["dairy", "gluten"],
    name: "Creamy Tuscan Chicken Pasta",
    emoji: "🍝",
    time: 35,
    tags: ["Italian", "Comfort"],
    ingredients: [
      { item: "Penne pasta", amount: "8 oz", dept: "Pantry", search: "penne pasta" },
      { item: "Chicken breasts", amount: "1 lb, cubed", dept: "Meat", search: "boneless chicken breast" },
      { item: "Heavy cream", amount: "1 cup", dept: "Dairy" },
      { item: "Sun-dried tomatoes", amount: "1/2 cup", dept: "Pantry", search: "sun dried tomatoes" },
      { item: "Baby spinach", amount: "3 cups", dept: "Produce" },
      { item: "Parmesan cheese", amount: "1/2 cup, grated", dept: "Dairy", search: "grated parmesan cheese" },
      { item: "Garlic", amount: "4 cloves", dept: "Produce" },
      { item: "Italian seasoning", amount: "1 tsp", dept: "Spices" },
    ],
    steps: [
      "Cook penne per package directions; reserve 1/2 cup pasta water.",
      "Season and sear cubed chicken until golden; remove.",
      "Sauté garlic and sun-dried tomatoes 1 minute, then add cream and Italian seasoning.",
      "Stir in parmesan until melted, then wilt in the spinach.",
      "Toss with pasta and chicken, loosening with pasta water as needed.",
    ],
  },
  {
    id: "sheet-pan-sausage",
    allergens: [],
    name: "Sheet Pan Sausage & Veggies",
    emoji: "🍳",
    time: 35,
    tags: ["One Pan", "Easy Cleanup"],
    ingredients: [
      { item: "Smoked sausage", amount: "14 oz, sliced", dept: "Meat", search: "smoked sausage" },
      { item: "Baby potatoes", amount: "1 lb, halved", dept: "Produce", search: "baby gold potatoes" },
      { item: "Broccoli", amount: "1 head, in florets", dept: "Produce", search: "broccoli crowns" },
      { item: "Red onion", amount: "1, in wedges", dept: "Produce" },
      { item: "Olive oil", amount: "3 tbsp", dept: "Pantry" },
      { item: "Smoked paprika", amount: "1 tsp", dept: "Spices" },
      { item: "Garlic powder", amount: "1 tsp", dept: "Spices" },
    ],
    steps: [
      "Preheat oven to 425°F.",
      "Toss potatoes with oil and spices; roast 15 minutes alone.",
      "Add sausage, broccoli, and onion tossed with remaining oil.",
      "Roast 15–20 more minutes until potatoes are tender and edges crisp.",
    ],
  },
  {
    id: "honey-garlic-shrimp",
    allergens: ["shellfish", "soy"],
    name: "Honey Garlic Shrimp Stir-Fry",
    emoji: "🍤",
    time: 20,
    tags: ["Seafood", "Quick", "Asian"],
    ingredients: [
      { item: "Large shrimp", amount: "1 lb, peeled", dept: "Seafood", search: "raw shrimp peeled" },
      { item: "Honey", amount: "1/4 cup", dept: "Pantry" },
      { item: "Soy sauce", amount: "1/4 cup", dept: "International", search: "soy sauce" },
      { item: "Garlic", amount: "4 cloves", dept: "Produce" },
      { item: "Fresh ginger", amount: "1 tbsp, grated", dept: "Produce", search: "fresh ginger root" },
      { item: "Snow peas", amount: "2 cups", dept: "Produce" },
      { item: "Jasmine rice", amount: "1 cup, uncooked", dept: "International", search: "jasmine rice" },
      { item: "Green onions", amount: "2, sliced", dept: "Produce" },
    ],
    steps: [
      "Start rice per package directions.",
      "Whisk honey, soy sauce, garlic, and ginger into a sauce.",
      "Sear shrimp 1–2 minutes per side in a hot pan; remove.",
      "Stir-fry snow peas 2 minutes, add sauce and simmer until glossy.",
      "Return shrimp to coat, then serve over rice with green onions.",
    ],
  },
  {
    id: "turkey-burgers",
    allergens: ["dairy", "gluten", "eggs"],
    name: "Juicy Turkey Burgers",
    emoji: "🍔",
    time: 25,
    tags: ["American", "Grill"],
    ingredients: [
      { item: "Ground turkey", amount: "1 lb", dept: "Meat", search: "93% lean ground turkey" },
      { item: "Brioche buns", amount: "2", dept: "Bakery", search: "brioche hamburger buns" },
      { item: "Cheddar cheese slices", amount: "2", dept: "Dairy", search: "sliced cheddar cheese" },
      { item: "Tomato", amount: "1, sliced", dept: "Produce", search: "tomatoes on the vine" },
      { item: "Romaine lettuce", amount: "2 leaves", dept: "Produce", search: "romaine lettuce" },
      { item: "Red onion", amount: "1/2, sliced", dept: "Produce" },
      { item: "Worcestershire sauce", amount: "1 tbsp", dept: "Pantry" },
      { item: "Mayonnaise", amount: "for serving", dept: "Pantry" },
      { item: "Sweet potato fries", amount: "1 bag", dept: "Frozen", search: "frozen sweet potato fries" },
    ],
    steps: [
      "Bake sweet potato fries per the bag while you cook.",
      "Mix turkey with Worcestershire, salt, and pepper; form 2 patties with a thumb dimple.",
      "Cook 4–5 minutes per side to 165°F, adding cheddar in the last minute.",
      "Toast buns, then build with mayo, lettuce, tomato, and onion.",
    ],
  },
  {
    id: "veggie-stir-fry-noodles",
    allergens: ["gluten", "soy", "eggs"],
    name: "Veggie Lo Mein Night",
    emoji: "🥡",
    time: 25,
    tags: ["Vegetarian", "Asian", "Quick"],
    ingredients: [
      { item: "Lo mein noodles", amount: "8 oz", dept: "International", search: "lo mein noodles" },
      { item: "Broccoli", amount: "2 cups florets", dept: "Produce", search: "broccoli crowns" },
      { item: "Carrots", amount: "2, julienned", dept: "Produce" },
      { item: "Mushrooms", amount: "8 oz, sliced", dept: "Produce", search: "baby bella mushrooms" },
      { item: "Soy sauce", amount: "3 tbsp", dept: "International", search: "soy sauce" },
      { item: "Sesame oil", amount: "1 tbsp", dept: "International", search: "toasted sesame oil" },
      { item: "Garlic", amount: "3 cloves", dept: "Produce" },
      { item: "Eggs", amount: "2", dept: "Dairy", search: "large eggs" },
    ],
    steps: [
      "Boil noodles per package; drain and toss with a little sesame oil.",
      "Scramble eggs in the wok; set aside.",
      "Stir-fry mushrooms, broccoli, and carrots with garlic until crisp-tender.",
      "Add noodles, soy sauce, and sesame oil; toss over high heat.",
      "Fold in the eggs and serve hot.",
    ],
  },
  {
    id: "slow-cooker-chili",
    allergens: ["dairy", "gluten"],
    name: "Cozy Beef Chili",
    emoji: "🍲",
    time: 45,
    tags: ["Comfort", "Make Ahead"],
    ingredients: [
      { item: "Ground beef", amount: "1 lb", dept: "Meat", search: "ground beef 80/20" },
      { item: "Kidney beans", amount: "1 can (15 oz)", dept: "Pantry", search: "canned kidney beans" },
      { item: "Black beans", amount: "1 can (15 oz)", dept: "Pantry", search: "canned black beans" },
      { item: "Crushed tomatoes", amount: "1 can (28 oz)", dept: "Pantry", search: "canned crushed tomatoes" },
      { item: "Yellow onion", amount: "1, diced", dept: "Produce" },
      { item: "Chili powder", amount: "2 tbsp", dept: "Spices" },
      { item: "Cumin", amount: "1 tbsp", dept: "Spices", search: "ground cumin" },
      { item: "Shredded cheddar", amount: "for topping", dept: "Dairy", search: "shredded cheddar cheese" },
      { item: "Cornbread mix", amount: "1 box", dept: "Pantry", search: "cornbread mix" },
    ],
    steps: [
      "Brown beef with onion; drain excess fat.",
      "Add spices and toast 1 minute, then add tomatoes and drained beans.",
      "Simmer at least 30 minutes (longer is better), stirring occasionally.",
      "Bake cornbread per the box while the chili simmers.",
      "Serve topped with shredded cheddar.",
    ],
  },
  {
    id: "caprese-chicken",
    allergens: ["dairy"],
    name: "Caprese Chicken",
    emoji: "🍅",
    time: 30,
    tags: ["Italian", "Light"],
    ingredients: [
      { item: "Chicken breasts", amount: "2", dept: "Meat", search: "boneless chicken breast" },
      { item: "Fresh mozzarella", amount: "4 oz, sliced", dept: "Deli", search: "fresh mozzarella" },
      { item: "Tomatoes", amount: "2, sliced", dept: "Produce", search: "tomatoes on the vine" },
      { item: "Fresh basil", amount: "1 bunch", dept: "Produce" },
      { item: "Balsamic glaze", amount: "2 tbsp", dept: "Pantry", search: "balsamic glaze" },
      { item: "Green beans", amount: "12 oz", dept: "Produce", search: "fresh green beans" },
      { item: "Olive oil", amount: "2 tbsp", dept: "Pantry" },
    ],
    steps: [
      "Season chicken and sear in olive oil 5–6 minutes per side until cooked through.",
      "Top each breast with tomato and mozzarella; cover until cheese melts.",
      "Steam green beans 4–5 minutes until crisp-tender.",
      "Plate, drizzle with balsamic glaze, and shower with torn basil.",
    ],
  },
  {
    id: "shrimp-tacos",
    allergens: ["shellfish", "dairy"],
    name: "Blackened Shrimp Tacos",
    emoji: "🌮",
    time: 25,
    tags: ["Seafood", "Mexican", "Quick"],
    ingredients: [
      { item: "Large shrimp", amount: "1 lb, peeled", dept: "Seafood", search: "raw shrimp peeled" },
      { item: "Corn tortillas", amount: "8 small", dept: "International", search: "corn tortillas" },
      { item: "Coleslaw mix", amount: "1 bag", dept: "Produce", search: "coleslaw mix" },
      { item: "Avocado", amount: "1", dept: "Produce" },
      { item: "Lime", amount: "2", dept: "Produce" },
      { item: "Cilantro", amount: "1/2 bunch", dept: "Produce", search: "fresh cilantro" },
      { item: "Blackened seasoning", amount: "2 tbsp", dept: "Spices" },
      { item: "Sour cream", amount: "1/2 cup", dept: "Dairy" },
    ],
    steps: [
      "Toss slaw mix with lime juice, half the cilantro, and a pinch of salt.",
      "Stir sour cream with lime juice into a quick crema.",
      "Coat shrimp in blackened seasoning and sear 1–2 minutes per side.",
      "Warm tortillas, then build: slaw, shrimp, avocado, crema, cilantro.",
    ],
  },
  {
    id: "baked-ziti",
    allergens: ["dairy", "gluten"],
    name: "Weeknight Baked Ziti",
    emoji: "🧀",
    time: 45,
    tags: ["Italian", "Comfort", "Leftovers"],
    ingredients: [
      { item: "Ziti pasta", amount: "12 oz", dept: "Pantry", search: "ziti pasta" },
      { item: "Italian sausage", amount: "1 lb", dept: "Meat", search: "ground italian sausage" },
      { item: "Marinara sauce", amount: "1 jar (24 oz)", dept: "Pantry", search: "marinara sauce" },
      { item: "Ricotta cheese", amount: "1 cup", dept: "Dairy", search: "ricotta cheese" },
      { item: "Shredded mozzarella", amount: "2 cups", dept: "Dairy", search: "shredded mozzarella" },
      { item: "Parmesan cheese", amount: "1/2 cup", dept: "Dairy", search: "grated parmesan cheese" },
      { item: "Garlic bread", amount: "1 loaf", dept: "Frozen", search: "frozen garlic bread" },
    ],
    steps: [
      "Preheat oven to 375°F. Boil ziti 2 minutes shy of al dente.",
      "Brown sausage, then stir in marinara.",
      "Toss pasta with sauce and dollops of ricotta in a baking dish.",
      "Top with mozzarella and parmesan; bake 20 minutes until bubbly.",
      "Bake garlic bread alongside for the last 10 minutes.",
    ],
  },
  {
    id: "greek-chicken-bowls",
    allergens: ["dairy", "gluten"],
    name: "Greek Chicken Bowls",
    emoji: "🥗",
    time: 30,
    tags: ["Mediterranean", "Healthy"],
    ingredients: [
      { item: "Chicken thighs", amount: "1 lb, boneless", dept: "Meat", search: "boneless chicken thighs" },
      { item: "Cucumber", amount: "1, diced", dept: "Produce" },
      { item: "Cherry tomatoes", amount: "1 pint", dept: "Produce" },
      { item: "Red onion", amount: "1/2, diced", dept: "Produce" },
      { item: "Feta cheese", amount: "1/2 cup, crumbled", dept: "Dairy", search: "crumbled feta cheese" },
      { item: "Kalamata olives", amount: "1/2 cup", dept: "Deli", search: "kalamata olives" },
      { item: "Tzatziki", amount: "1/2 cup", dept: "Deli", search: "tzatziki" },
      { item: "Couscous", amount: "1 cup, uncooked", dept: "Pantry", search: "pearl couscous" },
      { item: "Dried oregano", amount: "1 tbsp", dept: "Spices" },
      { item: "Lemon", amount: "1", dept: "Produce" },
    ],
    steps: [
      "Marinate chicken in olive oil, lemon juice, oregano, salt, and pepper (10+ minutes).",
      "Cook couscous per package directions.",
      "Sear chicken 5–6 minutes per side; rest, then slice.",
      "Build bowls: couscous, chicken, cucumber, tomatoes, onion, olives, feta.",
      "Finish with tzatziki and a squeeze of lemon.",
    ],
  },
  {
    id: "pork-chops-apples",
    allergens: ["dairy"],
    name: "Skillet Pork Chops & Apples",
    emoji: "🍎",
    time: 30,
    tags: ["American", "Fall Favorite"],
    ingredients: [
      { item: "Pork chops", amount: "2 bone-in", dept: "Meat", search: "bone-in pork chops" },
      { item: "Honeycrisp apples", amount: "2, sliced", dept: "Produce", search: "honeycrisp apples" },
      { item: "Yellow onion", amount: "1, sliced", dept: "Produce" },
      { item: "Butter", amount: "2 tbsp", dept: "Dairy", search: "unsalted butter" },
      { item: "Fresh thyme", amount: "4 sprigs", dept: "Produce", search: "fresh thyme" },
      { item: "Apple cider", amount: "1/2 cup", dept: "Pantry", search: "apple cider" },
      { item: "Mashed potatoes", amount: "1 package", dept: "Dairy", search: "refrigerated mashed potatoes" },
    ],
    steps: [
      "Season chops and sear in butter 4–5 minutes per side; remove to rest.",
      "Sauté apples and onion in the same skillet until soft and golden.",
      "Deglaze with apple cider, add thyme, and simmer to a glaze.",
      "Heat mashed potatoes; serve chops over them, smothered in apples.",
    ],
  },
  {
    id: "margherita-flatbreads",
    allergens: ["dairy", "gluten"],
    name: "Margherita Flatbreads & Salad",
    emoji: "🍕",
    time: 20,
    tags: ["Vegetarian", "Quick", "Date Night"],
    ingredients: [
      { item: "Naan or flatbreads", amount: "2", dept: "Bakery", search: "naan bread" },
      { item: "Marinara sauce", amount: "1/2 cup", dept: "Pantry", search: "pizza sauce" },
      { item: "Fresh mozzarella", amount: "8 oz", dept: "Deli", search: "fresh mozzarella" },
      { item: "Fresh basil", amount: "1 bunch", dept: "Produce" },
      { item: "Spring mix", amount: "1 bag", dept: "Produce", search: "spring mix salad" },
      { item: "Balsamic vinaigrette", amount: "1/4 cup", dept: "Pantry", search: "balsamic vinaigrette" },
      { item: "Cherry tomatoes", amount: "1 cup", dept: "Produce" },
    ],
    steps: [
      "Preheat oven to 450°F.",
      "Top flatbreads with sauce, torn mozzarella, and halved cherry tomatoes.",
      "Bake 8–10 minutes until cheese bubbles and edges crisp.",
      "Toss spring mix with vinaigrette.",
      "Scatter basil over the flatbreads, slice, and serve with salad.",
    ],
  },
];
